<a href="https://colab.research.google.com/github/Tatyana-Stoyanova/CRC-Algorithm/blob/main/CompNetze_A2_Hardware.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Modelieren Sie die Hardware-Implementierung eines CRC-Algorithmus mit einem standarten Bluetooth-Polynom.
Zeigen Sie wie die Fehlererkennung funktioniert.

Bluetooth-Polynom:

x^16 + x^12 + x^5 + 1 = 10001000000100001

In [ ]:
import numpy as np

In [ ]:
def isBinary(a):
  for i in range(0,len(a)):
    if (a[i] != 0 and a[i] != 1):
      return False    
  return True

In [ ]:
#Nachricht zum Senden eintragen
print("Tragen Sie eine Binärnummer ein:")
binary=False
while(binary==False):
  nachricht = [int(i) for i in input() if i.isdigit()]
  nachricht = np.array(nachricht)
  if(isBinary(nachricht) == False):
    print("Diese Nummer ist nicht binär! Versuchen Sie noch ein Mal!")
    continue
  else:
    print("Die engetragene Binärnummer ist die Nachricht, dass zum Senden ist!")
    binary=True
nachricht


Tragen Sie eine Binärnummer ein:
1010
Die engetragene Binärnummer ist die Nachricht, dass zum Senden ist!


array([1, 0, 1, 0])

In [ ]:
#Grad des Blootooth-Generatorpolynoms 
r = 16

#Feedback-Register for Bluetooth-Generator-Polynom definieren
feedback_register=np.zeros(r,int)
feedback_register


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#Nachricht für die Durchgehen durch Feedback-Register vorbereiten
arr = np.zeros(r, int)
nachrichtZuSenden = np.concatenate([nachricht, arr])
nachrichtZuSenden

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
def XOR(a,b):
  if a == b:
     aXORb = 0
  else:
    aXORb = 1
  return aXORb 

In [ ]:
def move(a,b):
  x=b[0]
  for i in range (0, len(b)):
    if(i == 3): # x^13 = x^12 xor x^16
      b[i] = XOR(b[i+1],x)


    elif(i == 10): # x^6 = x^5 xor x^16
      b[i] = XOR(b[i+1],x)



    elif(i == 15): # x^1 = x^0 xor x^16
      b[i] = XOR(a, x)



    else:
      b[i] = b[i+1]
    print(b)



In [ ]:
#Nachricht durch Feedback-Register durchgehen
CRC_code = feedback_register.copy()
for i in range (0, len(nachrichtZuSenden)):
  move(nachrichtZuSenden[i],CRC_code)
CRC_code

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0

array([1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0])

In [ ]:
#Codierte Nachricht bestimmen
Codierte_Nachricht=np.concatenate([nachricht, CRC_code])
Codierte_Nachricht

array([1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0])

In [ ]:
#Für Fehler beim Senden prüfen
fehler = feedback_register.copy()
for i in range (0, len(Codierte_Nachricht)):
  move(Codierte_Nachricht[i],fehler)

count_fehler=0
for i in range (0, len(fehler)):
  if fehler[i]!=0:
    count_fehler+=1
if(count_fehler==0):
  print("Fehlerfreies Senden!")
else:
  print("Fehler beim Senden!")

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0

In [ ]:
#Fehler beim Senden simulieren
fehl = feedback_register.copy()

pos_fehler=len(nachricht)%r
fehlerhafteN= Codierte_Nachricht.copy()

if(fehlerhafteN[pos_fehler]==1):
  fehlerhafteN[pos_fehler]=0
elif(Codierte_Nachricht[pos_fehler]==0):
  fehlerhafteN[pos_fehler]=1

for i in range (0, len(fehlerhafteN)):
  move( fehlerhafteN[i],fehl)

fehler_count=0
for i in range (0, len(fehl)):
  if fehl[i]!=0:
    fehler_count+=1
if(fehler_count==0):
  print("Fehlerfreies Senden!")
else:
  print("Fehler beim Senden!")

Fehler beim Senden!
